#!/usr/bin/env php
<?php

require __DIR__.'/../src/bootstrap.php';

error_reporting(-1);
ini_set('display_errors', 1);

use Symfony\Component\Console\Application;
use Necromancer\Command\DefaultCommand;

$command = new DefaultCommand();
$application = new Application();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();